// @ts-check 启用 TypeScript 类型检查，有助于发现潜在错误

// 该文件在 Node.js 环境下运行，请勿在此处使用浏览器相关的 API（如 window、document、JSX 等）

/**
 * 创建侧边栏可以让你：
 * - 创建一组有序的文档
 * - 为每篇文档生成对应的侧边栏导航
 * - 提供“上一页 / 下一页”导航功能
 *
 * 侧边栏可以从文件系统结构自动生成，也可以在这里显式定义。
 * 你可以创建任意数量的侧边栏。
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  // 默认情况下，Docusaurus 会根据 docs 文件夹结构自动生成侧边栏
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 你也可以手动定义一个侧边栏（以下为示例，当前被注释掉）
  /*
  tutorialSidebar: [
    'intro',         // 对应 docs/intro.md
    'hello',         // 对应 docs/hello.md
    {
      type: 'category',     // 创建一个分类
      label: '教程',        // 分类标题
      items: ['tutorial-basics/create-a-document'], // 包含的文档路径
    },
  ],
  */
};

export default sidebars; // 导出配置供 Docusaurus 使用